name: Deploy resume to Cloud
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  deploy:
    name: Terraform Cloud Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Terraform init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform validate
        id: validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform apply
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile

  destroy:
    name: Destroy Cloud Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          id: init
          run: terraform init

        - name: Terraform destroy
          id: destroy
          run: terraform destroy -auto-approve -input=false
        